import { BudgetItem, CategoryItem, GoalItem, SettingsData, TransactionItem, UserProfile } from './types';

export const INITIAL_USER_PROFILE: UserProfile = {
  name: 'Ashish Singh',
  email: 'ashish.singh@example.com',
  currency: 'INR ₹',
  monthlyIncome: 65000,
  monthlyBudget: 35000,
  preferredCategories: [
    'Food & Dining',
    'Shopping',
    'Transport',
    'Bills & Utilities',
    'Subscriptions',
    'Entertainment',
  ],
  memberSince: '12 Feb 2025',
  accountType: 'Premium Pro',
};

export const INITIAL_CATEGORIES: CategoryItem[] = [
  { id: 'cat-1', name: 'Food & Dining', iconType: 'food', colorHex: '#9CC9FF', spentAmount: 0, transactionCount: 0 },
  { id: 'cat-2', name: 'Shopping', iconType: 'shopping', colorHex: '#EF9C8D', spentAmount: 0, transactionCount: 0 },
  { id: 'cat-3', name: 'Transport', iconType: 'transport', colorHex: '#C9B8FF', spentAmount: 0, transactionCount: 0 },
  { id: 'cat-4', name: 'Bills & Utilities', iconType: 'bills', colorHex: '#F5D98A', spentAmount: 0, transactionCount: 0 },
  { id: 'cat-5', name: 'Subscriptions', iconType: 'subscription', colorHex: '#B9DEC9', spentAmount: 0, transactionCount: 0 },
  { id: 'cat-6', name: 'Entertainment', iconType: 'entertainment', colorHex: '#F4C7B5', spentAmount: 0, transactionCount: 0 },
  { id: 'cat-7', name: 'Healthcare', iconType: 'health', colorHex: '#EF9C8D', spentAmount: 0, transactionCount: 0 },
  { id: 'cat-8', name: 'Education', iconType: 'education', colorHex: '#9CC9FF', spentAmount: 0, transactionCount: 0 },
  { id: 'cat-9', name: 'Travel', iconType: 'travel', colorHex: '#F4C7B5', spentAmount: 0, transactionCount: 0 },
  { id: 'cat-10', name: 'Other', iconType: 'other', colorHex: '#B9DEC9', spentAmount: 0, transactionCount: 0 },
];

export const INITIAL_BUDGETS: BudgetItem[] = [
  {
    id: 'budget-oct-2026',
    name: 'October Plan',
    month: 'October 2026',
    totalLimit: 35000,
    spent: 0,
    alertThresholdPercent: 90,
    allocations: [
      { categoryName: 'Food & Dining', percentage: 28, amount: 10000, colorHex: '#9CC9FF', iconType: 'food' },
      { categoryName: 'Shopping', percentage: 23, amount: 8000, colorHex: '#EF9C8D', iconType: 'shopping' },
      { categoryName: 'Transport', percentage: 14, amount: 5000, colorHex: '#C9B8FF', iconType: 'transport' },
      { categoryName: 'Bills & Utilities', percentage: 14, amount: 5000, colorHex: '#F5D98A', iconType: 'bills' },
      { categoryName: 'Subscriptions', percentage: 10, amount: 3500, colorHex: '#B9DEC9', iconType: 'subscription' },
      { categoryName: 'Entertainment', percentage: 11, amount: 3500, colorHex: '#F4C7B5', iconType: 'entertainment' },
    ],
  },
  {
    id: 'budget-sep-2026',
    name: 'September Plan',
    month: 'September 2026',
    totalLimit: 34000,
    spent: 0,
    alertThresholdPercent: 90,
    allocations: [
      { categoryName: 'Food & Dining', percentage: 30, amount: 10000, colorHex: '#9CC9FF', iconType: 'food' },
      { categoryName: 'Shopping', percentage: 24, amount: 8000, colorHex: '#EF9C8D', iconType: 'shopping' },
      { categoryName: 'Transport', percentage: 15, amount: 5000, colorHex: '#C9B8FF', iconType: 'transport' },
      { categoryName: 'Bills & Utilities', percentage: 15, amount: 5000, colorHex: '#F5D98A', iconType: 'bills' },
      { categoryName: 'Subscriptions', percentage: 10, amount: 3500, colorHex: '#B9DEC9', iconType: 'subscription' },
      { categoryName: 'Entertainment', percentage: 6, amount: 2500, colorHex: '#F4C7B5', iconType: 'entertainment' },
    ],
  },
  {
    id: 'budget-aug-2026',
    name: 'August Plan',
    month: 'August 2026',
    totalLimit: 32000,
    spent: 0,
    alertThresholdPercent: 90,
    allocations: [
      { categoryName: 'Food & Dining', percentage: 31, amount: 10000, colorHex: '#9CC9FF', iconType: 'food' },
      { categoryName: 'Shopping', percentage: 22, amount: 7000, colorHex: '#EF9C8D', iconType: 'shopping' },
      { categoryName: 'Transport', percentage: 16, amount: 5000, colorHex: '#C9B8FF', iconType: 'transport' },
      { categoryName: 'Bills & Utilities', percentage: 16, amount: 5000, colorHex: '#F5D98A', iconType: 'bills' },
      { categoryName: 'Subscriptions', percentage: 9, amount: 3000, colorHex: '#B9DEC9', iconType: 'subscription' },
      { categoryName: 'Entertainment', percentage: 6, amount: 2000, colorHex: '#F4C7B5', iconType: 'entertainment' },
    ],
  },
];

export const INITIAL_GOALS: GoalItem[] = [
  {
    id: 'goal-laptop',
    name: 'New MacBook Pro M4',
    targetAmount: 85000,
    currentSavings: 45000,
    targetDate: '30 Nov 2026',
    category: 'Electronics',
    iconType: 'laptop',
    colorHex: '#9CC9FF',
    description: 'High performance workstation for engineering and creative productivity.',
    contributions: [
      { id: 'c-101', amount: 10000, date: '12 Sep 2026', note: 'Salary bonus savings' },
      { id: 'c-102', amount: 15000, date: '28 Aug 2026', note: 'Freelance project savings' },
      { id: 'c-103', amount: 12000, date: '15 Jul 2026', note: 'Quarterly savings deposit' },
      { id: 'c-104', amount: 8000, date: '20 Jun 2026', note: 'Initial savings deposit' },
    ],
  },
  {
    id: 'goal-emergency',
    name: 'Emergency Safety Buffer',
    targetAmount: 150000,
    currentSavings: 80000,
    targetDate: '31 Dec 2026',
    category: 'Savings',
    iconType: 'shield',
    colorHex: '#F5D98A',
    description: '6 months of living expenses safely preserved for total peace of mind.',
    contributions: [
      { id: 'c-201', amount: 20000, date: '01 Oct 2026', note: 'Monthly safety buffer allocation' },
      { id: 'c-202', amount: 25000, date: '01 Sep 2026', note: 'Systematic allocation' },
      { id: 'c-203', amount: 20000, date: '01 Aug 2026', note: 'Systematic allocation' },
      { id: 'c-204', amount: 15000, date: '01 Jul 2026', note: 'Emergency reserve fund' },
    ],
  },
  {
    id: 'goal-goa',
    name: 'Goa Beach Vacation',
    targetAmount: 30000,
    currentSavings: 30000,
    targetDate: '15 Oct 2026',
    category: 'Travel',
    iconType: 'beach',
    colorHex: '#F4C7B5',
    description: 'Golden sunsets, beach shack dining, and relaxation with college friends.',
    contributions: [
      { id: 'c-301', amount: 10000, date: '25 Sep 2026', note: 'Resort final payment' },
      { id: 'c-302', amount: 8000, date: '10 Aug 2026', note: 'Flight bookings deposit' },
      { id: 'c-303', amount: 7000, date: '15 Jul 2026', note: 'Activities & water sports pool' },
      { id: 'c-304', amount: 5000, date: '05 Jun 2026', note: 'Early vacation seed fund' },
    ],
  },
  {
    id: 'goal-bike',
    name: 'Ather Electric Scooter',
    targetAmount: 130000,
    currentSavings: 47000,
    targetDate: '28 Feb 2027',
    category: 'Vehicle',
    iconType: 'bike',
    colorHex: '#B9DEC9',
    description: 'Eco-friendly daily city commute to eliminate fuel expenses.',
    contributions: [
      { id: 'c-401', amount: 15000, date: '18 Sep 2026', note: 'Downpayment savings' },
      { id: 'c-402', amount: 20000, date: '20 Aug 2026', note: 'Festive bonus savings' },
      { id: 'c-403', amount: 12000, date: '10 Jul 2026', note: 'Commute fund deposit' },
    ],
  },
  {
    id: 'goal-phone',
    name: 'iPhone 16 Pro Upgrade',
    targetAmount: 75000,
    currentSavings: 20000,
    targetDate: '31 Mar 2027',
    category: 'Gadgets',
    iconType: 'laptop',
    colorHex: '#C9B8FF',
    description: 'Upgraded mobile hardware for 4K video capture and testing.',
    contributions: [
      { id: 'c-501', amount: 12000, date: '28 Sep 2026', note: 'Trade-in preparation pool' },
      { id: 'c-502', amount: 8000, date: '05 Aug 2026', note: 'Camera upgrade fund' },
    ],
  },
];

export const INITIAL_TRANSACTIONS: TransactionItem[] = [
  // =================== OCTOBER 2026 (CURRENT MONTH) ===================
  {
    id: 'tx-01',
    title: 'Starbucks Iced Latte',
    subtitle: 'Food & Dining',
    amount: 350,
    type: 'EXPENSE',
    category: 'Food & Dining',
    date: 'Today',
    time: '09:15 AM',
    paymentMethod: 'UPI',
    tags: ['Coffee', 'Casual'],
    notes: 'Morning hazelnut iced latte before standup.',
    iconType: 'coffee',
    colorHex: '#9CC9FF',
  },
  {
    id: 'tx-02',
    title: 'Blinkit Essentials',
    subtitle: 'Food & Dining',
    amount: 480,
    type: 'EXPENSE',
    category: 'Food & Dining',
    date: 'Today',
    time: '10:45 AM',
    paymentMethod: 'UPI',
    tags: ['Groceries', 'Daily'],
    notes: 'Fresh vegetables, sourdough bread, and milk.',
    iconType: 'groceries',
    colorHex: '#9CC9FF',
  },
  {
    id: 'tx-03',
    title: 'Monthly Tech Salary Credit',
    subtitle: 'Salary',
    amount: 65000,
    type: 'INCOME',
    category: 'Salary',
    date: 'Today',
    time: '07:00 AM',
    paymentMethod: 'Bank Transfer',
    tags: ['Income', 'Monthly'],
    notes: 'Direct deposit salary from Tech Corp India.',
    iconType: 'salary',
    colorHex: '#B9DEC9',
  },
  {
    id: 'tx-04',
    title: 'Swiggy Dinner Combo',
    subtitle: 'Food & Dining',
    amount: 420,
    type: 'EXPENSE',
    category: 'Food & Dining',
    date: 'Yesterday',
    time: '08:30 PM',
    paymentMethod: 'UPI',
    tags: ['Dinner', 'Delivery'],
    notes: 'Healthy paneer quinoa bowl.',
    iconType: 'food',
    colorHex: '#9CC9FF',
  },
  {
    id: 'tx-05',
    title: 'Netflix 4K UHD Plan',
    subtitle: 'Subscriptions',
    amount: 649,
    type: 'EXPENSE',
    category: 'Subscriptions',
    date: 'Yesterday',
    time: '06:00 AM',
    paymentMethod: 'HDFC Credit Card',
    tags: ['Subscription', 'Recurring'],
    notes: 'Monthly recurring entertainment streaming subscription.',
    iconType: 'subscription',
    colorHex: '#B9DEC9',
  },
  {
    id: 'tx-06',
    title: 'Spotify Premium Family',
    subtitle: 'Subscriptions',
    amount: 179,
    type: 'EXPENSE',
    category: 'Subscriptions',
    date: 'Yesterday',
    time: '06:15 AM',
    paymentMethod: 'UPI',
    tags: ['Subscription', 'Recurring'],
    notes: 'Monthly high-fidelity music streaming.',
    iconType: 'subscription',
    colorHex: '#B9DEC9',
  },
  {
    id: 'tx-07',
    title: 'Airtel Xstream Fiber Wi-Fi',
    subtitle: 'Bills & Utilities',
    amount: 999,
    type: 'EXPENSE',
    category: 'Bills & Utilities',
    date: 'Yesterday',
    time: '11:20 AM',
    paymentMethod: 'UPI',
    tags: ['Utility', 'Recurring'],
    notes: '300 Mbps unlimited optical broadband.',
    iconType: 'bills',
    colorHex: '#F5D98A',
  },
  {
    id: 'tx-08',
    title: 'Amazon Noise-Cancelling Headphones',
    subtitle: 'Shopping',
    amount: 4999,
    type: 'EXPENSE',
    category: 'Shopping',
    date: '02 Oct 2026',
    time: '02:40 PM',
    paymentMethod: 'HDFC Credit Card',
    tags: ['Electronics', 'Work'],
    notes: 'Sony ANC headphones for focused deep work.',
    iconType: 'shopping',
    colorHex: '#EF9C8D',
  },
  {
    id: 'tx-09',
    title: 'Zara Autumn Casual Outfit',
    subtitle: 'Shopping',
    amount: 3500,
    type: 'EXPENSE',
    category: 'Shopping',
    date: '02 Oct 2026',
    time: '05:15 PM',
    paymentMethod: 'HDFC Credit Card',
    tags: ['Apparel', 'Style'],
    notes: 'Smart casual blazer and knit sweater.',
    iconType: 'shopping',
    colorHex: '#EF9C8D',
  },
  {
    id: 'tx-10',
    title: 'Nike Revolution Running Shoes',
    subtitle: 'Shopping',
    amount: 2800,
    type: 'EXPENSE',
    category: 'Shopping',
    date: '02 Oct 2026',
    time: '06:30 PM',
    paymentMethod: 'Debit Card',
    tags: ['Fitness', 'Footwear'],
    notes: 'Lightweight road running shoes for morning workout.',
    iconType: 'shopping',
    colorHex: '#EF9C8D',
  },
  {
    id: 'tx-11',
    title: 'Uber Premier Office Commute',
    subtitle: 'Transport',
    amount: 380,
    type: 'EXPENSE',
    category: 'Transport',
    date: '01 Oct 2026',
    time: '09:00 AM',
    paymentMethod: 'Credit Card',
    tags: ['Commute'],
    notes: 'Morning rush hour taxi to technology park.',
    iconType: 'transport',
    colorHex: '#C9B8FF',
  },
  {
    id: 'tx-12',
    title: 'Zomato Team Lunch',
    subtitle: 'Food & Dining',
    amount: 850,
    type: 'EXPENSE',
    category: 'Food & Dining',
    date: '01 Oct 2026',
    time: '01:15 PM',
    paymentMethod: 'UPI',
    tags: ['Work', 'Lunch'],
    notes: 'South Indian thali combo with engineering team.',
    iconType: 'food',
    colorHex: '#9CC9FF',
  },
  {
    id: 'tx-13',
    title: 'Electricity Bill BESCOM',
    subtitle: 'Bills & Utilities',
    amount: 2250,
    type: 'EXPENSE',
    category: 'Bills & Utilities',
    date: '01 Oct 2026',
    time: '12:00 PM',
    paymentMethod: 'UPI',
    tags: ['Electricity', 'Home'],
    notes: 'Monthly household electricity power consumption.',
    iconType: 'bills',
    colorHex: '#F5D98A',
  },
  {
    id: 'tx-14',
    title: "Gold's Gym Monthly Pass",
    subtitle: 'Subscriptions',
    amount: 1800,
    type: 'EXPENSE',
    category: 'Subscriptions',
    date: '01 Oct 2026',
    time: '07:30 AM',
    paymentMethod: 'UPI',
    tags: ['Fitness', 'Recurring'],
    notes: 'Monthly strength & conditioning membership.',
    iconType: 'subscription',
    colorHex: '#B9DEC9',
  },
  {
    id: 'tx-15',
    title: 'Petrol Shell V-Power',
    subtitle: 'Transport',
    amount: 1650,
    type: 'EXPENSE',
    category: 'Transport',
    date: '01 Oct 2026',
    time: '04:45 PM',
    paymentMethod: 'Cash',
    tags: ['Fuel'],
    notes: 'Full tank fuel for weekend drive.',
    iconType: 'transport',
    colorHex: '#C9B8FF',
  },
  {
    id: 'tx-16',
    title: 'Nature Basket Organic Mart',
    subtitle: 'Food & Dining',
    amount: 2850,
    type: 'EXPENSE',
    category: 'Food & Dining',
    date: '01 Oct 2026',
    time: '07:15 PM',
    paymentMethod: 'Debit Card',
    tags: ['Groceries', 'Organic'],
    notes: 'Fortified oats, cold-pressed oils, and Greek yoghurt.',
    iconType: 'food',
    colorHex: '#9CC9FF',
  },
  {
    id: 'tx-17',
    title: 'PVR INOX IMAX Experience',
    subtitle: 'Entertainment',
    amount: 750,
    type: 'EXPENSE',
    category: 'Entertainment',
    date: '02 Oct 2026',
    time: '09:00 PM',
    paymentMethod: 'UPI',
    tags: ['Cinema', 'Weekend'],
    notes: 'IMAX Sci-Fi movie screening.',
    iconType: 'entertainment',
    colorHex: '#F4C7B5',
  },

  // =================== SEPTEMBER 2026 ===================
  {
    id: 'tx-18',
    title: 'Freelance Web Design Retainer',
    subtitle: 'Salary',
    amount: 18000,
    type: 'INCOME',
    category: 'Salary',
    date: '28 Sep 2026',
    time: '05:00 PM',
    paymentMethod: 'Bank Transfer',
    tags: ['Freelance', 'SideIncome'],
    notes: 'Milestone 2 frontend UI delivery for FinTech client.',
    iconType: 'salary',
    colorHex: '#B9DEC9',
  },
  {
    id: 'tx-19',
    title: 'Swiggy Weekend Feast',
    subtitle: 'Food & Dining',
    amount: 1250,
    type: 'EXPENSE',
    category: 'Food & Dining',
    date: '26 Sep 2026',
    time: '08:45 PM',
    paymentMethod: 'UPI',
    tags: ['Dinner'],
    notes: 'Artisan wood-fired pizza and dessert with friends.',
    iconType: 'food',
    colorHex: '#9CC9FF',
  },
  {
    id: 'tx-20',
    title: 'Apple Store USB-C Accessories',
    subtitle: 'Shopping',
    amount: 3400,
    type: 'EXPENSE',
    category: 'Shopping',
    date: '24 Sep 2026',
    time: '03:15 PM',
    paymentMethod: 'HDFC Credit Card',
    tags: ['Tech'],
    notes: 'Original fast charger and thunderbolt cable.',
    iconType: 'shopping',
    colorHex: '#EF9C8D',
  },
  {
    id: 'tx-21',
    title: 'Uber Cab to Airport',
    subtitle: 'Transport',
    amount: 720,
    type: 'EXPENSE',
    category: 'Transport',
    date: '22 Sep 2026',
    time: '05:30 AM',
    paymentMethod: 'UPI',
    tags: ['Travel', 'Airport'],
    notes: 'Early morning airport drop.',
    iconType: 'transport',
    colorHex: '#C9B8FF',
  },
  {
    id: 'tx-22',
    title: 'Weekly Grocery Supermart',
    subtitle: 'Food & Dining',
    amount: 3100,
    type: 'EXPENSE',
    category: 'Food & Dining',
    date: '20 Sep 2026',
    time: '11:00 AM',
    paymentMethod: 'Debit Card',
    tags: ['Groceries'],
    notes: 'Bi-weekly kitchen staples and dry fruits.',
    iconType: 'food',
    colorHex: '#9CC9FF',
  },
  {
    id: 'tx-23',
    title: 'PVR Tickets + Gourmet Snacks',
    subtitle: 'Entertainment',
    amount: 1100,
    type: 'EXPENSE',
    category: 'Entertainment',
    date: '18 Sep 2026',
    time: '07:30 PM',
    paymentMethod: 'UPI',
    tags: ['Movie'],
    notes: 'Weekend cinema outing.',
    iconType: 'entertainment',
    colorHex: '#F4C7B5',
  },
  {
    id: 'tx-24',
    title: 'Monthly Mobile Postpaid Bill',
    subtitle: 'Bills & Utilities',
    amount: 599,
    type: 'EXPENSE',
    category: 'Bills & Utilities',
    date: '15 Sep 2026',
    time: '02:00 PM',
    paymentMethod: 'UPI',
    tags: ['Mobile', 'Recurring'],
    notes: 'Jio postpaid 5G connection.',
    iconType: 'bills',
    colorHex: '#F5D98A',
  },
  {
    id: 'tx-25',
    title: 'Dinner with Family Barbeque',
    subtitle: 'Food & Dining',
    amount: 2650,
    type: 'EXPENSE',
    category: 'Food & Dining',
    date: '12 Sep 2026',
    time: '08:00 PM',
    paymentMethod: 'HDFC Credit Card',
    tags: ['Family', 'Celebration'],
    notes: 'Barbeque Nation buffet dinner.',
    iconType: 'food',
    colorHex: '#9CC9FF',
  },
  {
    id: 'tx-26',
    title: 'Fuel Indian Oil',
    subtitle: 'Transport',
    amount: 1500,
    type: 'EXPENSE',
    category: 'Transport',
    date: '10 Sep 2026',
    time: '09:30 AM',
    paymentMethod: 'Cash',
    tags: ['Fuel'],
    notes: 'Refuel bike tank.',
    iconType: 'transport',
    colorHex: '#C9B8FF',
  },
  {
    id: 'tx-27',
    title: 'Uniqlo T-Shirts & Chinos',
    subtitle: 'Shopping',
    amount: 4200,
    type: 'EXPENSE',
    category: 'Shopping',
    date: '08 Sep 2026',
    time: '04:15 PM',
    paymentMethod: 'HDFC Credit Card',
    tags: ['Clothing'],
    notes: 'Airism cotton crew neck shirts.',
    iconType: 'shopping',
    colorHex: '#EF9C8D',
  },
  {
    id: 'tx-28',
    title: 'Blinkit Quick Breakfast',
    subtitle: 'Food & Dining',
    amount: 380,
    type: 'EXPENSE',
    category: 'Food & Dining',
    date: '05 Sep 2026',
    time: '08:10 AM',
    paymentMethod: 'UPI',
    tags: ['Breakfast'],
    notes: 'Cereals and almond milk.',
    iconType: 'food',
    colorHex: '#9CC9FF',
  },
  {
    id: 'tx-29',
    title: 'Monthly Salary Credit',
    subtitle: 'Salary',
    amount: 65000,
    type: 'INCOME',
    category: 'Salary',
    date: '01 Sep 2026',
    time: '07:00 AM',
    paymentMethod: 'Bank Transfer',
    tags: ['Income'],
    notes: 'Monthly corporate salary credit.',
    iconType: 'salary',
    colorHex: '#B9DEC9',
  },
  {
    id: 'tx-30',
    title: 'Netflix 4K UHD Plan',
    subtitle: 'Subscriptions',
    amount: 649,
    type: 'EXPENSE',
    category: 'Subscriptions',
    date: '01 Sep 2026',
    time: '06:00 AM',
    paymentMethod: 'HDFC Credit Card',
    tags: ['Subscription', 'Recurring'],
    notes: 'Automated monthly recurring charge.',
    iconType: 'subscription',
    colorHex: '#B9DEC9',
  },
  {
    id: 'tx-31',
    title: 'Spotify Premium Family',
    subtitle: 'Subscriptions',
    amount: 179,
    type: 'EXPENSE',
    category: 'Subscriptions',
    date: '01 Sep 2026',
    time: '06:15 AM',
    paymentMethod: 'UPI',
    tags: ['Subscription', 'Recurring'],
    notes: 'Automated monthly recurring music.',
    iconType: 'subscription',
    colorHex: '#B9DEC9',
  },
  {
    id: 'tx-32',
    title: 'Home Broadband Internet',
    subtitle: 'Bills & Utilities',
    amount: 999,
    type: 'EXPENSE',
    category: 'Bills & Utilities',
    date: '01 Sep 2026',
    time: '11:00 AM',
    paymentMethod: 'UPI',
    tags: ['Utility', 'Recurring'],
    notes: 'Fiber internet renewal.',
    iconType: 'bills',
    colorHex: '#F5D98A',
  },
  {
    id: 'tx-33',
    title: 'Apartment Maintenance Society',
    subtitle: 'Bills & Utilities',
    amount: 3000,
    type: 'EXPENSE',
    category: 'Bills & Utilities',
    date: '01 Sep 2026',
    time: '01:00 PM',
    paymentMethod: 'Net Banking',
    tags: ['Housing'],
    notes: 'Society building maintenance and water.',
    iconType: 'bills',
    colorHex: '#F5D98A',
  },

  // =================== AUGUST 2026 ===================
  {
    id: 'tx-34',
    title: 'Freelance Consulting Invoice',
    subtitle: 'Salary',
    amount: 15000,
    type: 'INCOME',
    category: 'Salary',
    date: '28 Aug 2026',
    time: '04:30 PM',
    paymentMethod: 'Bank Transfer',
    tags: ['Freelance'],
    notes: 'Technical consulting & advisory work.',
    iconType: 'salary',
    colorHex: '#B9DEC9',
  },
  {
    id: 'tx-35',
    title: 'Reliance Digital 4K Monitor',
    subtitle: 'Shopping',
    amount: 14999, // Unusually large expense (ANOMALY)
    type: 'EXPENSE',
    category: 'Shopping',
    date: '25 Aug 2026',
    time: '06:20 PM',
    paymentMethod: 'HDFC Credit Card',
    tags: ['Electronics', 'Anomaly'],
    notes: '27-inch 4K IPS HDR monitor for desk setup.',
    iconType: 'shopping',
    colorHex: '#EF9C8D',
  },
  {
    id: 'tx-36',
    title: 'Swiggy Gourmet Bowls',
    subtitle: 'Food & Dining',
    amount: 540,
    type: 'EXPENSE',
    category: 'Food & Dining',
    date: '22 Aug 2026',
    time: '01:10 PM',
    paymentMethod: 'UPI',
    tags: ['Lunch'],
    notes: 'Warm Mexican burrito bowl.',
    iconType: 'food',
    colorHex: '#9CC9FF',
  },
  {
    id: 'tx-37',
    title: 'Blinkit Household Restock',
    subtitle: 'Food & Dining',
    amount: 1620,
    type: 'EXPENSE',
    category: 'Food & Dining',
    date: '20 Aug 2026',
    time: '09:40 AM',
    paymentMethod: 'UPI',
    tags: ['Groceries'],
    notes: 'Cooking essentials, spices, and olive oil.',
    iconType: 'food',
    colorHex: '#9CC9FF',
  },
  {
    id: 'tx-38',
    title: 'Uber City Ride',
    subtitle: 'Transport',
    amount: 260,
    type: 'EXPENSE',
    category: 'Transport',
    date: '18 Aug 2026',
    time: '04:15 PM',
    paymentMethod: 'UPI',
    tags: ['Commute'],
    notes: 'Ride to co-working hub.',
    iconType: 'transport',
    colorHex: '#C9B8FF',
  },
  {
    id: 'tx-39',
    title: 'Independence Day Brunch',
    subtitle: 'Food & Dining',
    amount: 1850,
    type: 'EXPENSE',
    category: 'Food & Dining',
    date: '15 Aug 2026',
    time: '12:30 PM',
    paymentMethod: 'Credit Card',
    tags: ['Brunch', 'Holiday'],
    notes: 'Celebratory holiday cafe brunch.',
    iconType: 'food',
    colorHex: '#9CC9FF',
  },
  {
    id: 'tx-40',
    title: 'Apollo Pharmacy Medicines',
    subtitle: 'Healthcare',
    amount: 820,
    type: 'EXPENSE',
    category: 'Healthcare',
    date: '12 Aug 2026',
    time: '07:45 PM',
    paymentMethod: 'UPI',
    tags: ['Health'],
    notes: 'Vitamins, supplements, and first aid.',
    iconType: 'health',
    colorHex: '#EF9C8D',
  },
  {
    id: 'tx-41',
    title: 'Shell Petrol Topup',
    subtitle: 'Transport',
    amount: 1400,
    type: 'EXPENSE',
    category: 'Transport',
    date: '10 Aug 2026',
    time: '08:15 AM',
    paymentMethod: 'Debit Card',
    tags: ['Fuel'],
    notes: 'Vehicle tank refilled.',
    iconType: 'transport',
    colorHex: '#C9B8FF',
  },
  {
    id: 'tx-42',
    title: 'Myntra Lifestyle Apparel',
    subtitle: 'Shopping',
    amount: 2100,
    type: 'EXPENSE',
    category: 'Shopping',
    date: '05 Aug 2026',
    time: '03:30 PM',
    paymentMethod: 'UPI',
    tags: ['Fashion'],
    notes: 'Denim jeans and socks bundle.',
    iconType: 'shopping',
    colorHex: '#EF9C8D',
  },
  {
    id: 'tx-43',
    title: 'Monthly Salary Credit',
    subtitle: 'Salary',
    amount: 65000,
    type: 'INCOME',
    category: 'Salary',
    date: '01 Aug 2026',
    time: '07:00 AM',
    paymentMethod: 'Bank Transfer',
    tags: ['Income'],
    notes: 'Tech Corp monthly deposit.',
    iconType: 'salary',
    colorHex: '#B9DEC9',
  },
  {
    id: 'tx-44',
    title: 'Netflix 4K UHD Plan',
    subtitle: 'Subscriptions',
    amount: 649,
    type: 'EXPENSE',
    category: 'Subscriptions',
    date: '01 Aug 2026',
    time: '06:00 AM',
    paymentMethod: 'HDFC Credit Card',
    tags: ['Subscription', 'Recurring'],
    notes: 'Monthly recurring charge.',
    iconType: 'subscription',
    colorHex: '#B9DEC9',
  },
  {
    id: 'tx-45',
    title: 'Spotify Premium Family',
    subtitle: 'Subscriptions',
    amount: 179,
    type: 'EXPENSE',
    category: 'Subscriptions',
    date: '01 Aug 2026',
    time: '06:15 AM',
    paymentMethod: 'UPI',
    tags: ['Subscription', 'Recurring'],
    notes: 'Monthly recurring charge.',
    iconType: 'subscription',
    colorHex: '#B9DEC9',
  },
  {
    id: 'tx-46',
    title: 'Home Broadband Internet',
    subtitle: 'Bills & Utilities',
    amount: 999,
    type: 'EXPENSE',
    category: 'Bills & Utilities',
    date: '01 Aug 2026',
    time: '11:00 AM',
    paymentMethod: 'UPI',
    tags: ['Utility', 'Recurring'],
    notes: 'Broadband connection fee.',
    iconType: 'bills',
    colorHex: '#F5D98A',
  },
  {
    id: 'tx-47',
    title: 'Electricity Bill BESCOM',
    subtitle: 'Bills & Utilities',
    amount: 2450,
    type: 'EXPENSE',
    category: 'Bills & Utilities',
    date: '01 Aug 2026',
    time: '02:30 PM',
    paymentMethod: 'UPI',
    tags: ['Electricity'],
    notes: 'August air conditioning usage.',
    iconType: 'bills',
    colorHex: '#F5D98A',
  },

  // =================== JULY 2026 ===================
  {
    id: 'tx-48',
    title: 'Swiggy Dinner Bowls',
    subtitle: 'Food & Dining',
    amount: 580,
    type: 'EXPENSE',
    category: 'Food & Dining',
    date: '30 Jul 2026',
    time: '08:15 PM',
    paymentMethod: 'UPI',
    tags: ['Dinner'],
    notes: 'Evening salad & pasta meal.',
    iconType: 'food',
    colorHex: '#9CC9FF',
  },
  {
    id: 'tx-49',
    title: 'Supermarket Restock',
    subtitle: 'Food & Dining',
    amount: 3450,
    type: 'EXPENSE',
    category: 'Food & Dining',
    date: '26 Jul 2026',
    time: '11:30 AM',
    paymentMethod: 'Debit Card',
    tags: ['Groceries'],
    notes: 'Weekly wholefoods and dairy items.',
    iconType: 'food',
    colorHex: '#9CC9FF',
  },
  {
    id: 'tx-50',
    title: 'Uber City Commute',
    subtitle: 'Transport',
    amount: 420,
    type: 'EXPENSE',
    category: 'Transport',
    date: '22 Jul 2026',
    time: '06:15 PM',
    paymentMethod: 'UPI',
    tags: ['Commute'],
    notes: 'Cab ride after rain shower.',
    iconType: 'transport',
    colorHex: '#C9B8FF',
  },
  {
    id: 'tx-51',
    title: 'BookMyShow Live Music Concert',
    subtitle: 'Entertainment',
    amount: 2500,
    type: 'EXPENSE',
    category: 'Entertainment',
    date: '18 Jul 2026',
    time: '08:00 PM',
    paymentMethod: 'HDFC Credit Card',
    tags: ['Music', 'Concert'],
    notes: 'Live acoustic music gig with friends.',
    iconType: 'entertainment',
    colorHex: '#F4C7B5',
  },
  {
    id: 'tx-52',
    title: 'Fuel Petrol Tank',
    subtitle: 'Transport',
    amount: 1500,
    type: 'EXPENSE',
    category: 'Transport',
    date: '15 Jul 2026',
    time: '09:00 AM',
    paymentMethod: 'Cash',
    tags: ['Fuel'],
    notes: 'Mid-month refuel.',
    iconType: 'transport',
    colorHex: '#C9B8FF',
  },
  {
    id: 'tx-53',
    title: 'Zomato Bistro Dinner',
    subtitle: 'Food & Dining',
    amount: 790,
    type: 'EXPENSE',
    category: 'Food & Dining',
    date: '12 Jul 2026',
    time: '07:45 PM',
    paymentMethod: 'UPI',
    tags: ['Dining'],
    notes: 'Italian pasta and lemonade.',
    iconType: 'food',
    colorHex: '#9CC9FF',
  },
  {
    id: 'tx-54',
    title: 'Udemy Distributed Systems Course',
    subtitle: 'Education',
    amount: 1299,
    type: 'EXPENSE',
    category: 'Education',
    date: '08 Jul 2026',
    time: '10:00 PM',
    paymentMethod: 'UPI',
    tags: ['Learning'],
    notes: 'Cloud architecture certification study.',
    iconType: 'education',
    colorHex: '#9CC9FF',
  },
  {
    id: 'tx-55',
    title: 'Blinkit Quick Groceries',
    subtitle: 'Food & Dining',
    amount: 890,
    type: 'EXPENSE',
    category: 'Food & Dining',
    date: '05 Jul 2026',
    time: '08:45 AM',
    paymentMethod: 'UPI',
    tags: ['Groceries'],
    notes: 'Fruits, green tea, and bread.',
    iconType: 'food',
    colorHex: '#9CC9FF',
  },
  {
    id: 'tx-56',
    title: 'Monthly Salary Credit',
    subtitle: 'Salary',
    amount: 65000,
    type: 'INCOME',
    category: 'Salary',
    date: '01 Jul 2026',
    time: '07:00 AM',
    paymentMethod: 'Bank Transfer',
    tags: ['Income'],
    notes: 'Corporate salary deposit.',
    iconType: 'salary',
    colorHex: '#B9DEC9',
  },
  {
    id: 'tx-57',
    title: 'Netflix 4K UHD Plan',
    subtitle: 'Subscriptions',
    amount: 649,
    type: 'EXPENSE',
    category: 'Subscriptions',
    date: '01 Jul 2026',
    time: '06:00 AM',
    paymentMethod: 'HDFC Credit Card',
    tags: ['Subscription', 'Recurring'],
    notes: 'Recurring streaming subscription.',
    iconType: 'subscription',
    colorHex: '#B9DEC9',
  },
  {
    id: 'tx-58',
    title: 'Spotify Premium Family',
    subtitle: 'Subscriptions',
    amount: 179,
    type: 'EXPENSE',
    category: 'Subscriptions',
    date: '01 Jul 2026',
    time: '06:15 AM',
    paymentMethod: 'UPI',
    tags: ['Subscription', 'Recurring'],
    notes: 'Recurring music subscription.',
    iconType: 'subscription',
    colorHex: '#B9DEC9',
  },
  {
    id: 'tx-59',
    title: 'Home Broadband Internet',
    subtitle: 'Bills & Utilities',
    amount: 999,
    type: 'EXPENSE',
    category: 'Bills & Utilities',
    date: '01 Jul 2026',
    time: '11:00 AM',
    paymentMethod: 'UPI',
    tags: ['Utility', 'Recurring'],
    notes: 'Monthly broadband billing.',
    iconType: 'bills',
    colorHex: '#F5D98A',
  },

  // =================== JUNE 2026 ===================
  {
    id: 'tx-60',
    title: 'Amazon Kindle Paperwhite',
    subtitle: 'Shopping',
    amount: 8999,
    type: 'EXPENSE',
    category: 'Shopping',
    date: '27 Jun 2026',
    time: '02:00 PM',
    paymentMethod: 'HDFC Credit Card',
    tags: ['Reading', 'Gadgets'],
    notes: 'Glare-free reading display.',
    iconType: 'shopping',
    colorHex: '#EF9C8D',
  },
  {
    id: 'tx-61',
    title: 'Swiggy Food Delivery',
    subtitle: 'Food & Dining',
    amount: 610,
    type: 'EXPENSE',
    category: 'Food & Dining',
    date: '24 Jun 2026',
    time: '01:30 PM',
    paymentMethod: 'UPI',
    tags: ['Lunch'],
    notes: 'Biryani bowl and raita.',
    iconType: 'food',
    colorHex: '#9CC9FF',
  },
  {
    id: 'tx-62',
    title: 'Namma Metro Card Recharge',
    subtitle: 'Transport',
    amount: 1000,
    type: 'EXPENSE',
    category: 'Transport',
    date: '20 Jun 2026',
    time: '09:00 AM',
    paymentMethod: 'UPI',
    tags: ['Transit'],
    notes: 'Smart card auto-topup for monthly metro.',
    iconType: 'transport',
    colorHex: '#C9B8FF',
  },
  {
    id: 'tx-63',
    title: 'Groceries BigBasket',
    subtitle: 'Food & Dining',
    amount: 2900,
    type: 'EXPENSE',
    category: 'Food & Dining',
    date: '16 Jun 2026',
    time: '10:15 AM',
    paymentMethod: 'Debit Card',
    tags: ['Groceries'],
    notes: 'Pantry staples, pulses, basmati rice.',
    iconType: 'food',
    colorHex: '#9CC9FF',
  },
  {
    id: 'tx-64',
    title: 'PVR Movie Night IMAX',
    subtitle: 'Entertainment',
    amount: 880,
    type: 'EXPENSE',
    category: 'Entertainment',
    date: '12 Jun 2026',
    time: '06:45 PM',
    paymentMethod: 'UPI',
    tags: ['Cinema'],
    notes: 'Weekend evening movie ticket.',
    iconType: 'entertainment',
    colorHex: '#F4C7B5',
  },
  {
    id: 'tx-65',
    title: 'Dental Checkup & Polishing',
    subtitle: 'Healthcare',
    amount: 1500,
    type: 'EXPENSE',
    category: 'Healthcare',
    date: '08 Jun 2026',
    time: '05:00 PM',
    paymentMethod: 'UPI',
    tags: ['Dental'],
    notes: 'Bi-annual dental clinic consultation.',
    iconType: 'health',
    colorHex: '#EF9C8D',
  },
  {
    id: 'tx-66',
    title: 'Monthly Salary Credit',
    subtitle: 'Salary',
    amount: 65000,
    type: 'INCOME',
    category: 'Salary',
    date: '01 Jun 2026',
    time: '07:00 AM',
    paymentMethod: 'Bank Transfer',
    tags: ['Income'],
    notes: 'Monthly corporate salary.',
    iconType: 'salary',
    colorHex: '#B9DEC9',
  },
  {
    id: 'tx-67',
    title: 'Netflix 4K UHD Plan',
    subtitle: 'Subscriptions',
    amount: 649,
    type: 'EXPENSE',
    category: 'Subscriptions',
    date: '01 Jun 2026',
    time: '06:00 AM',
    paymentMethod: 'HDFC Credit Card',
    tags: ['Subscription', 'Recurring'],
    notes: 'Streaming subscription fee.',
    iconType: 'subscription',
    colorHex: '#B9DEC9',
  },
  {
    id: 'tx-68',
    title: 'Spotify Premium Family',
    subtitle: 'Subscriptions',
    amount: 179,
    type: 'EXPENSE',
    category: 'Subscriptions',
    date: '01 Jun 2026',
    time: '06:15 AM',
    paymentMethod: 'UPI',
    tags: ['Subscription', 'Recurring'],
    notes: 'Streaming audio fee.',
    iconType: 'subscription',
    colorHex: '#B9DEC9',
  },
  {
    id: 'tx-69',
    title: 'Home Broadband Internet',
    subtitle: 'Bills & Utilities',
    amount: 999,
    type: 'EXPENSE',
    category: 'Bills & Utilities',
    date: '01 Jun 2026',
    time: '11:00 AM',
    paymentMethod: 'UPI',
    tags: ['Utility', 'Recurring'],
    notes: 'High-speed internet.',
    iconType: 'bills',
    colorHex: '#F5D98A',
  },

  // =================== MAY 2026 ===================
  {
    id: 'tx-70',
    title: 'Decathlon Sports & Running Gear',
    subtitle: 'Shopping',
    amount: 3200,
    type: 'EXPENSE',
    category: 'Shopping',
    date: '28 May 2026',
    time: '04:00 PM',
    paymentMethod: 'UPI',
    tags: ['Sports'],
    notes: 'Dri-fit activewear and gym water bottle.',
    iconType: 'shopping',
    colorHex: '#EF9C8D',
  },
  {
    id: 'tx-71',
    title: 'Olive Bistro Dinner',
    subtitle: 'Food & Dining',
    amount: 2100,
    type: 'EXPENSE',
    category: 'Food & Dining',
    date: '24 May 2026',
    time: '08:30 PM',
    paymentMethod: 'HDFC Credit Card',
    tags: ['Dining'],
    notes: 'Dinner date at Italian bistro.',
    iconType: 'food',
    colorHex: '#9CC9FF',
  },
  {
    id: 'tx-72',
    title: 'Blinkit Weekly Kitchen Supplies',
    subtitle: 'Food & Dining',
    amount: 1150,
    type: 'EXPENSE',
    category: 'Food & Dining',
    date: '20 May 2026',
    time: '09:10 AM',
    paymentMethod: 'UPI',
    tags: ['Groceries'],
    notes: 'Daily groceries delivery.',
    iconType: 'food',
    colorHex: '#9CC9FF',
  },
  {
    id: 'tx-73',
    title: 'Uber City Commute',
    subtitle: 'Transport',
    amount: 480,
    type: 'EXPENSE',
    category: 'Transport',
    date: '15 May 2026',
    time: '06:00 PM',
    paymentMethod: 'UPI',
    tags: ['Commute'],
    notes: 'Ride back home.',
    iconType: 'transport',
    colorHex: '#C9B8FF',
  },
  {
    id: 'tx-74',
    title: 'Petrol Fuel Indian Oil',
    subtitle: 'Transport',
    amount: 1400,
    type: 'EXPENSE',
    category: 'Transport',
    date: '10 May 2026',
    time: '08:00 AM',
    paymentMethod: 'Cash',
    tags: ['Fuel'],
    notes: 'Monthly motorcycle fuel.',
    iconType: 'transport',
    colorHex: '#C9B8FF',
  },
  {
    id: 'tx-75',
    title: 'Apollo Pharmacy Health Supplements',
    subtitle: 'Healthcare',
    amount: 650,
    type: 'EXPENSE',
    category: 'Healthcare',
    date: '05 May 2026',
    time: '07:30 PM',
    paymentMethod: 'UPI',
    tags: ['Health'],
    notes: 'Multivitamins and protein bars.',
    iconType: 'health',
    colorHex: '#EF9C8D',
  },
  {
    id: 'tx-76',
    title: 'Monthly Salary Credit',
    subtitle: 'Salary',
    amount: 65000,
    type: 'INCOME',
    category: 'Salary',
    date: '01 May 2026',
    time: '07:00 AM',
    paymentMethod: 'Bank Transfer',
    tags: ['Income'],
    notes: 'Corporate direct deposit.',
    iconType: 'salary',
    colorHex: '#B9DEC9',
  },
  {
    id: 'tx-77',
    title: 'Netflix 4K UHD Plan',
    subtitle: 'Subscriptions',
    amount: 649,
    type: 'EXPENSE',
    category: 'Subscriptions',
    date: '01 May 2026',
    time: '06:00 AM',
    paymentMethod: 'HDFC Credit Card',
    tags: ['Subscription', 'Recurring'],
    notes: 'Automated recurring fee.',
    iconType: 'subscription',
    colorHex: '#B9DEC9',
  },
  {
    id: 'tx-78',
    title: 'Spotify Premium Family',
    subtitle: 'Subscriptions',
    amount: 179,
    type: 'EXPENSE',
    category: 'Subscriptions',
    date: '01 May 2026',
    time: '06:15 AM',
    paymentMethod: 'UPI',
    tags: ['Subscription', 'Recurring'],
    notes: 'Automated recurring fee.',
    iconType: 'subscription',
    colorHex: '#B9DEC9',
  },
  {
    id: 'tx-79',
    title: 'Home Broadband Internet',
    subtitle: 'Bills & Utilities',
    amount: 999,
    type: 'EXPENSE',
    category: 'Bills & Utilities',
    date: '01 May 2026',
    time: '11:00 AM',
    paymentMethod: 'UPI',
    tags: ['Utility', 'Recurring'],
    notes: 'Broadband optical fiber.',
    iconType: 'bills',
    colorHex: '#F5D98A',
  },
];

export const INITIAL_SETTINGS: SettingsData = {
  themeMode: 'LIGHT',
  isBalanceVisible: true,
  totalBalance: 78500,
  monthlyIncome: 65000,
  monthlyExpenses: 38000,
};

